import type { Metadata } from "next";
import { Geist_Mono, DM_Sans } from "next/font/google";
import { Toaster } from "react-hot-toast";
import { LoadingAnimation } from "@/components/custom-ui/loading-animation";
import "./globals.css";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const DmSans = DM_Sans({
  display: "swap",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={`${DmSans.className} ${geistMono.variable} antialiased`}
      >
        <LoadingAnimation />
        <Toaster position="top-center" reverseOrder={false} />
        {children}
      </body>
    </html>
  );
}
